### PR TITLE
feat(ra_xyze): Implemented ra_xyze command and options

### PR DESCRIPTION
**Pull request by mikkelkp**

### CODE REVIEW

**Review by chriswmackey — APPROVED** [review]
This all looks good to me, @mikkelkp . Thank you for adding it!

**Review by chriswmackey — APPROVED** [review]
This all looks good to me, @mikkelkp . Thank you for adding it!

**Review by mostaphaRoudsari — APPROVED** [review]
I have never used this command. You should feel free to merge it in after @sariths and @chriswmackey give you a green light. @chriswmackey is happy with the PR so it should be good to go.

**Comment by mostaphaRoudsari** [comment]
I merged it in on your behalf to make your life easier.

**Pull request merged**
